pub const DEFAULT_SERVER_PORT: u16 = 3000;

pub const DEFAULT_RATE_LIMIT_PER_SECOND: u32 = 10;

pub const DEFAULT_RECONNECT_DELAY_MS: u64 = 1000;

pub const DEFAULT_MAX_RECONNECT_ATTEMPTS: u32 = 10;

pub const DEFAULT_HEARTBEAT_INTERVAL_MS: u64 = 30000;

pub const DEFAULT_MAX_SIGNAL_AGE_SECONDS: u64 = 300;

pub const DEFAULT_SIGNAL_DEDUPLICATION_WINDOW_MS: u64 = 5000;

pub const DEFAULT_STALE_ORDERBOOK_THRESHOLD_MS: u64 = 10000;

pub const DEFAULT_MAX_CONCURRENT_SIGNALS: u32 = 100;

pub const DEFAULT_RETENTION_DAYS: u32 = 90;

pub const DEFAULT_MAX_SIGNALS_IN_MEMORY: usize = 10000;

pub const DEFAULT_CLEANUP_INTERVAL_HOURS: u64 = 24;

pub const DEFAULT_MAX_FILE_SIZE_MB: u64 = 100;

pub const DEFAULT_MAX_FILES: u32 = 10;

pub const DEFAULT_FILE_ENABLED: bool = true;

pub const DEFAULT_JSON_FORMAT: bool = false;

pub const DEFAULT_DESKTOP_NOTIFICATIONS: bool = true;

pub const DEFAULT_SOUND_ENABLED: bool = false;

pub const DEFAULT_NOTIFICATIONS_ENABLED: bool = true;

pub const DEFAULT_INVENTORY_CHECKS_ENABLED: bool = true;
